
site_name: phpgeo
repo_url: https://github.com/mjaschen/phpgeo
theme: readthedocs
site_author: Marcus Jaschen
extra_javascript:
  - piwik.js
pages:
  - Home: index.md
  - Installation: install.md
  - Calculations:
    - Distance/Length Calculations: calculations/distance.md
    - Bearing/Destination: calculations/bearing.md
    - Geofence: calculations/geofence.md
    - Transformations: calculations/transformations.md
  - Formatting and Output: formatting.md
  - Parsing and Input:
    - Coordinates: parser/coordinate.md
  - Geometry Objects:
    - Coordinate: geometry/coordinate.md
    - Ellipsoid: geometry/ellipsoid.md
    - Line: geometry/line.md
    - Polyline: geometry/polyline.md
    - Polygon: geometry/polygon.md

markdown_extensions:
  - toc
